### ISSUE TITLE
Little issue on all() method

### ISSUE THREAD

**Issue by nanotime** [carrot/roots-dynamic-content#7]
Guys, i found a new issue on the all() method. When someone try to get all posts or some nested dynamic content, like:

```
!=JSON.stringify(site.posts.all())
```

If the post folder don't have a .jade file to render out of nested folders, the prompt return:

```
Object  has no method 'all'
  at Error (<anonymous>:null:null)
  at on_error (/usr/local/lib/node_modules/roots/lib/cli/watch.js:67:21)
  at Roots.<anonymous> (/usr/local/lib/node_modules/roots/lib/cli/watch.js:45:14)
  at Roots.EventEmitter.emit (events.js:95:17)
  at Compile.<anonymous> (/usr/local/lib/node_modules/roots/lib/api/compile.js:66:20)
  at tryCatchReject (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:790:14)
  at RejectedHandler.when (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:658:9)
  at DeferredHandler.run (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:444:13)
  at Scheduler._drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/scheduler.js:56:14)
  at Scheduler.drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/scheduler.js:21:9)
  at process._tickCallback (node.js:415:13)
```

So, more clear:

```
posts
  nested
    bleh
  nested2
    bleh
```

Will be: **ERAAAWWWRRR! Bitch**

```
posts
  bleh-not-nested <-- not nested .jade file
  nested
    bleh
  nested2
    bleh
```

Will be: **Fuck yeah!**

Annd, I realized that the test (in dynamic-content project) is not covered the case of a nest without .jade files above.

So, this is it, If I can, I will write a test just to prove that part ... I just need to read the documentation and I pray that everything goes well, I have never written tests.

Cheers!!!

**Comment by thiagodebastos** [comment]
I have been struggling with this issue for quite some time now, for some reason even with the _render: false YAML front-matter it still gets rendered. Also, `post._categories[-1]` returns undefined, meaning I have to set it to [1] which is correct for all but the dummie.jade file, which then becomes undefined. I only just understood why that happens too!

**Comment by jenius** [comment]
Ah I'm sorry, I totally forgot about this. I'll take a look into it soon. This is just a small bug that should be fixable in the code. If you want to take a look feel free -- if not I'll get to it as soon as I can!

**Comment by thiagodebastos** [comment]
I wish I could, I am very much a newcomer to js and node and have not much of an idea as to where to begin to look in the code, I'm sorry  that I can't save you the time!

**Comment by nanotime** [comment]
Well, hello hello! I just come here to say hi (?) ... not really, but Hi! xD

Yup, the issue persists, bad juju, and one little thing, now when i put ```_render: false``` on the FM in the dummie content, it's rendered anyway.

For all other things, all fine.

PD: Wow, @jenius, roots has become something awesome!

**Comment by argyleink** [comment]
+1
